//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restautrent_order_service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("restautrent_order_service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _005195_03_black_purple_restaurant {
            get {
                object obj = ResourceManager.GetObject("005195-03-black-purple-restaurant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _05427bf7487b1c05d855ed669e41f29f {
            get {
                object obj = ResourceManager.GetObject("05427bf7487b1c05d855ed669e41f29f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1335329809detail_pry_no__ku06_06 {
            get {
                object obj = ResourceManager.GetObject("1335329809detail_pry-no__ku06_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1482193390408 {
            get {
                object obj = ResourceManager.GetObject("1482193390408", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1494363782441 {
            get {
                object obj = ResourceManager.GetObject("1494363782441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _23641553052_129dbb93b3_o {
            get {
                object obj = ResourceManager.GetObject("23641553052_129dbb93b3_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _26122847_IndigoRestaurant_cropped_1584x780 {
            get {
                object obj = ResourceManager.GetObject("26122847-IndigoRestaurant_cropped_1584x780", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _27697156_abstract_background_design_template {
            get {
                object obj = ResourceManager.GetObject("27697156-abstract-background-design-template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3208a43df27204445883e9c0474fc56a {
            get {
                object obj = ResourceManager.GetObject("3208a43df27204445883e9c0474fc56a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _42711471_abstract_purple_background_with_polygonal_design {
            get {
                object obj = ResourceManager.GetObject("42711471-abstract-purple-background-with-polygonal-design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _56051c3ebd78f {
            get {
                object obj = ResourceManager.GetObject("56051c3ebd78f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _679106_Coconut_Ice_Cream_Photo_by_Dianne_650x465 {
            get {
                object obj = ResourceManager.GetObject("679106-Coconut-Ice-Cream-Photo-by-Dianne-650x465", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _69127115_bright_texture_from_natural_amethyst_violet_crystal_background_for_your_jewelry_designs_ {
            get {
                object obj = ResourceManager.GetObject("69127115-bright-texture-from-natural-amethyst-violet-crystal-background-for-your-" +
                        "jewelry-designs-", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _69777_stracciatella_eis {
            get {
                object obj = ResourceManager.GetObject("69777-stracciatella-eis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7997_abstract_dark_purple_hexagonal_background_design {
            get {
                object obj = ResourceManager.GetObject("7997-abstract-dark-purple-hexagonal-background-design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7997_abstract_dark_purple_hexagonal_background_design1 {
            get {
                object obj = ResourceManager.GetObject("7997-abstract-dark-purple-hexagonal-background-design1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8c1ddcf3_ho_222_shamrock_shakes_thumbnail_s_en_US {
            get {
                object obj = ResourceManager.GetObject("8c1ddcf3-ho_222_shamrock-shakes_thumbnail_s_en-US", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8c1ddcf3_ho_222_shamrock_shakes_thumbnail_s_en_US1 {
            get {
                object obj = ResourceManager.GetObject("8c1ddcf3-ho_222_shamrock-shakes_thumbnail_s_en-US1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap amazing_design_different_types_of_cakes_designs_yummy {
            get {
                object obj = ResourceManager.GetObject("amazing-design-different-types-of-cakes-designs-yummy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arnotts_Freakshakes_003b {
            get {
                object obj = ResourceManager.GetObject("Arnotts-Freakshakes_003b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Badam_Kheer_Recipe_Indian_Spiced_Almond_Milk_1 {
            get {
                object obj = ResourceManager.GetObject("Badam_Kheer_Recipe_Indian_Spiced_Almond_Milk-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap baked_crispy_chicken {
            get {
                object obj = ResourceManager.GetObject("baked crispy chicken", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap best_ice_cream_recipes {
            get {
                object obj = ResourceManager.GetObject("best-ice-cream-recipes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap best_ice_cream_recipes1 {
            get {
                object obj = ResourceManager.GetObject("best-ice-cream-recipes1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bever_00030_horiz {
            get {
                object obj = ResourceManager.GetObject("bever_00030_horiz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Black_Icecream_Final_27_1 {
            get {
                object obj = ResourceManager.GetObject("Black-Icecream-Final-27-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bndodh {
            get {
                object obj = ResourceManager.GetObject("bndodh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bnho_candy_cane_ice {
            get {
                object obj = ResourceManager.GetObject("bnho candy cane ice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bnhyu {
            get {
                object obj = ResourceManager.GetObject("bnhyu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bnhyu1 {
            get {
                object obj = ResourceManager.GetObject("bnhyu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buche_noel_pomwonderful_230sq_000 {
            get {
                object obj = ResourceManager.GetObject("buche-noel-pomwonderful-230sq_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cake_straberry {
            get {
                object obj = ResourceManager.GetObject("cake straberry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cakesclub_vanilla_pineapple_cake {
            get {
                object obj = ResourceManager.GetObject("cakesclub_vanilla-pineapple-cake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cakesclub_vanilla_pineapple_cake1 {
            get {
                object obj = ResourceManager.GetObject("cakesclub_vanilla-pineapple-cake1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cartons_rich_creamy_black_cherry_chocolate_chunk {
            get {
                object obj = ResourceManager.GetObject("cartons_rich-creamy_black-cherry-chocolate-chunk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap celebration_cake_vanilla_cake_vanilla_buttercream_with_sprinkles_09cbb4820be1b4ad72d749971105e071 {
            get {
                object obj = ResourceManager.GetObject("celebration-cake-vanilla-cake-vanilla-buttercream-with-sprinkles.09cbb4820be1b4ad" +
                        "72d749971105e071", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chaomin {
            get {
                object obj = ResourceManager.GetObject("chaomin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatpataPaneer2 {
            get {
                object obj = ResourceManager.GetObject("ChatpataPaneer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Chicken_Pakora {
            get {
                object obj = ResourceManager.GetObject("Chicken-Pakora", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chicken_pear_and_blue_cheese_salad_40072_1 {
            get {
                object obj = ResourceManager.GetObject("chicken-pear-and-blue-cheese-salad-40072-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chocolate_hazelnut_coffee_milkshake_everydaydishes_com_H {
            get {
                object obj = ResourceManager.GetObject("chocolate-hazelnut-coffee-milkshake-everydaydishes_com-H", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Chocolate_Mirror_Cake_main {
            get {
                object obj = ResourceManager.GetObject("Chocolate_Mirror_Cake_main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chocolate_pastry_01_A {
            get {
                object obj = ResourceManager.GetObject("chocolate-pastry-01-A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crispy_Fish_Sticks_with_Tartar_Sauce_3 {
            get {
                object obj = ResourceManager.GetObject("Crispy-Fish-Sticks-with-Tartar-Sauce-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crispy_fried_prawn_cutlets_sweet_chilli_mayonnaise_50211119 {
            get {
                object obj = ResourceManager.GetObject("crispy-fried-prawn-cutlets-sweet-chilli-mayonnaise-50211119", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crystal_blue_texture_ice_white_light_background_dark_black_shadow_spots_bright_irregular_uneven_pattern_seamless_image_512x512 {
            get {
                object obj = ResourceManager.GetObject("crystal-blue-texture-ice-white-light-background-dark-black-shadow-spots-bright-ir" +
                        "regular-uneven-pattern-seamless-image-512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crystal_blue_texture_ice_white_light_background_dark_black_shadow_spots_bright_irregular_uneven_pattern_seamless_image_512x5121 {
            get {
                object obj = ResourceManager.GetObject("crystal-blue-texture-ice-white-light-background-dark-black-shadow-spots-bright-ir" +
                        "regular-uneven-pattern-seamless-image-512x5121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d0fbebeb_e166_4e56_9a4a_da0ebfb1ca2a {
            get {
                object obj = ResourceManager.GetObject("d0fbebeb-e166-4e56-9a4a-da0ebfb1ca2a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dal_Makhani {
            get {
                object obj = ResourceManager.GetObject("Dal-Makhani", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dessert_Tour_1_300x300 {
            get {
                object obj = ResourceManager.GetObject("Dessert-Tour_1-300x300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dream_background_with_flower_design_vector_03 {
            get {
                object obj = ResourceManager.GetObject("Dream-background-with-flower-design-vector-03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap easter_polka_dot_cake_3_1 {
            get {
                object obj = ResourceManager.GetObject("easter-polka-dot-cake-3-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap easy_sausage_and_potato_casserole {
            get {
                object obj = ResourceManager.GetObject("easy-sausage-and-potato-casserole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eggless_pineapple_pastry_620 {
            get {
                object obj = ResourceManager.GetObject("eggless-pineapple-pastry_620", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap emerald_mint_milkshake {
            get {
                object obj = ResourceManager.GetObject("emerald-mint-milkshake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hqdefault {
            get {
                object obj = ResourceManager.GetObject("hqdefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imagesfresh_strw {
            get {
                object obj = ResourceManager.GetObject("imagesfresh strw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_pimages_choco_pineapple_cakes_500x500 {
            get {
                object obj = ResourceManager.GetObject("img-pimages-choco-pineapple-cakes-500x500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img44439 {
            get {
                object obj = ResourceManager.GetObject("img44439", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img444391 {
            get {
                object obj = ResourceManager.GetObject("img444391", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img444392 {
            get {
                object obj = ResourceManager.GetObject("img444392", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Indigo_Restuarant_Award {
            get {
                object obj = ResourceManager.GetObject("Indigo-Restuarant-Award", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jk {
            get {
                object obj = ResourceManager.GetObject("jk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JuicePlusCompleteShakes {
            get {
                object obj = ResourceManager.GetObject("JuicePlusCompleteShakes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kesar_Pista_Kulfi_Recipe_Indian_Ice_Cream_1_2 {
            get {
                object obj = ResourceManager.GetObject("Kesar_Pista_Kulfi_Recipe_Indian_Ice_Cream-1-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maxresdefaultko {
            get {
                object obj = ResourceManager.GetObject("maxresdefaultko", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mkio {
            get {
                object obj = ResourceManager.GetObject("mkio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mmh_1062_trifle_horiz {
            get {
                object obj = ResourceManager.GetObject("mmh_1062_trifle_horiz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nagits {
            get {
                object obj = ResourceManager.GetObject("nagits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nutellaShakes_555x463 {
            get {
                object obj = ResourceManager.GetObject("nutellaShakes-555x463", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p5__2014_06_03_curry_soup_sweetpotato_coco_9999_24choco_taco_vegan {
            get {
                object obj = ResourceManager.GetObject("p5--2014_06_03_curry-soup-sweetpotato-coco_9999_24choco-taco-vegan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Palak_Paneer_1300x799 {
            get {
                object obj = ResourceManager.GetObject("Palak-Paneer-1300x799", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pasta_carbonara_79827_1 {
            get {
                object obj = ResourceManager.GetObject("pasta-carbonara-79827-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap purple_valentine_day_4044 {
            get {
                object obj = ResourceManager.GetObject("purple_valentine_day_4044", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rabri_20 {
            get {
                object obj = ResourceManager.GetObject("rabri-20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Red_wine_chocolate_shakes_web4 {
            get {
                object obj = ResourceManager.GetObject("Red-wine-chocolate-shakes-web4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reeses_cake_259101_173_0 {
            get {
                object obj = ResourceManager.GetObject("reeses-cake-259101-173_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Strawberry_Chocolate_Cake_1 {
            get {
                object obj = ResourceManager.GetObject("Strawberry-Chocolate-Cake-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled_3_4 {
            get {
                object obj = ResourceManager.GetObject("Untitled-3-4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
